### ISSUE TITLE
Import from KeepassXC not possible

### ISSUE THREAD

**Issue by madcoda9000** [Rabbit-Company/Passky-Website#2]
**Describe the bug**
It is not possible to import passwords from KeePassXC

**To Reproduce**
1. Export Passwords in KeepassXC: Database --> Export --> csv
2. open Passky-Website (hosted on own server) --> login --> klick import --> select KeepassXC 
3. paste thet data from keepassXC export
Example Data:

"Group","Title","Username","Password","URL","Notes","TOTP","Icon","Last Modified","Created"
"Root","Password1","username1","Password1","http://myruls.com","","","0","2021-11-05T14:42:48Z","2021-11-05T14:42:48Z"

The Message from Passky-Website is: Success: 0 Passwords imported

**Expected behavior**
I would expect that passky imported the password

**Additional context**
NOTE: Registering, Login, Creating of passwords, deleting of passwords, editing of passwords is working flawlessly!

**System Enviroment**

Passky-server
- Ubuntu 20.10
- installed with docker-compose
- published through apache reverse proxy (https with valid certificate)

Passkey-website
- ubuntu 20.10'
- published through apache (https with valid certificate)

Client
 - OS: [Windows 11]
 - Browser [edge]
 - Version [Version 95.0.1020.40 ]

**Comment by zigazajc007** [comment]
Hello,

Thanks for submitting an issue.

Passky import has currently some limitations:
1. Domain needs to be between 5 and 255 characters and can't contain any spaces. (Passky client will automatically remove "http://", "https://" and / at the end, to make domains more readable and also it would replace spaces with - )
2. Username needs to be between 3 and 255 characters.
3. Password needs to be between 5 and 255 characters.
4. Encrypted message must be under 10 000 characters.

If any of those criteria aren't matched, Passky will just skip import for this password and go to the next one.

Can you please provide me with how many passwords weren't imported and how many passwords did you imported?

If the ratio will be too big then I would need to reduce the criteria.
