### ISSUE TITLE
Passky Website requires an FQDN when there may not be one.

### ISSUE THREAD

**Issue by virtadpt** [Rabbit-Company/Passky-Website#3]
**Describe the bug**
I'm prototyping Passky on an isolated server at home to see if it would be a good fit for my family to use as a shared password manager.  Said server is internal only and has no FQDN, just a hostname.  When loading Passky-Website in my browser I entered the test URL into the Server field and got an error stating that it was an invalid URL.

**To Reproduce**
1. Install Passky-Server on a web server that doesn't have an FQDN, just a hostname: http://leandra/passky/api
2. Set up the Passky-Website web app on another server (I used my laptop)
3. Click the Sign Up button.
4. Enter the URL: http://leandra/passky/api
5. Enter a username, e-mail address, and password.
6. Tick the Terms of Service Box
7. Click the Sign Up button.
8. Get a modal window "ERROR Server url is invalid!"

**Expected behavior**
Passky-Website should contact my test Passky-Server install and create a new account in the database.

**Screenshots**
What I type in (redacted):
<img width="618" alt="Screen Shot 2022-01-13 at 13 11 12" src="https://user-images.githubusercontent.com/639730/149410039-1f5bad2d-6a20-413e-be6c-48bac6cc29aa.png">

What I get:
<img width="692" alt="Screen Shot 2022-01-13 at 13 09 13" src="https://user-images.githubusercontent.com/639730/149409681-fd732b23-b5b7-4a73-a1d5-d3864f15499f.png">

**Desktop (please complete the following information):**
 - MacOSX v10.15.7
 - Chrome v97.0.4692.71 (Official Build) (x86_64)

- Arch Linux, updated 20211214 (x86_64)
- Vivaldi v5.0.2497.30 (Stable channel) (stable) (64-bit)
- Firefox v94.0.1 (64-bit)

**Additional context**
Passky-Website served from my laptop for testing.

**Comment by zigazajc007** [comment]
Hello,

By default, the docker container for Passky Server will assign on port 8080 (This can be changed in docker-compose.yml file)

Can you try to use: http://**IP**:8080
Example for computer with IP 192.168.0.2:
`http://192.168.0.2:8080`

If you enter this URL in a browser you will need to see a json response:
`{"error":"400","info":"Action was not provided in GET!"}`

If you see this JSON response then it's working.

**Comment by virtadpt** [comment]
I did get that JSON response.  I also get that response if I cURL http://leandra/passky/api or load it in my browser.  It's only Passkey-Website that complains.

**Comment by zigazajc007** [comment]
Thanks. You can now change from
```js
function validURL(url){
    return new RegExp(/^(http|https):\/\/(([a-zA-Z0-9$\-_.+!*'(),;:&=]|%[0-9a-fA-F]{2})+@)?(((25[0-5]|2[0-4][0-9]|[0-1][0-9][0-9]|[1-9][0-9]|[0-9])(\.(25[0-5]|2[0-4][0-9]|[0-1][0-9][0-9]|[1-9][0-9]|[0-9])){3})|localhost|([a-zA-Z0-9\-\u00C0-\u017F]+\.)+([a-zA-Z]{2,}))(:[0-9]+)?(\/(([a-zA-Z0-9$\-_.+!*'(),;:@&=]|%[0-9a-fA-F]{2})*(\/([a-zA-Z0-9$\-_.+!*'(),;:@&=]|%[0-9a-fA-F]{2})*)*)?(\?([a-zA-Z0-9$\-_.+!*'(),;:@&=\/?]|%[0-9a-fA-F]{2})*)?(\#([a-zA-Z0-9$\-_.+!*'(),;:@&=\/?]|%[0-9a-fA-F]{2})*)?)?$/).test(url);
}
```
to:
```js
function validURL(url){
    return true;
}
```
This is a temporary fix that would work.
I will fix this in the next update.
Wish me luck with fixing Regex 😂

**Comment by virtadpt** [comment]
Yup - that worked.  And thank you!

**Comment by zigazajc007** [comment]
Fixed in version v6.0.0 which would be released today.

**Comment by tinker-rex-1** [comment]
> ```js
> function validURL
> ```

Where to edit this file ? I am getting the same issue

**Comment by zigazajc007** [comment]
> > ```js
> > function validURL
> > ```
> 
> Where to edit this file ? I am getting the same issue

Hello,

In the latest release URL validation has been moved to PasskyAPI.js file https://github.com/Rabbit-Company/Passky-Website/blob/f35f08f94aa5b2c073232cc2443a710a5f90af41/website/js/PasskyAPI.js#L15

This validation system will only check if the URL contains any space. So you shouldn't have those problems if you don't use any space in the URL.

If you don't have any space in your URL and still get this error message, make sure that you are using Passky Client v6.0.1.

If you use Passky Server v5.0.0 and need Passky Client v5.x.x, because of compatibility then you can edit this in default-functions.js  file.
